spring:
  application.name: clean-architecture
  datasource:
    url: jdbc:h2:mem:jpa;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
