CREATE TABLE if not exists  user_entity
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    active BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE if not exists item_entity
(
    id         BIGINT NOT NULL,
    name       VARCHAR(255),
    item_value DOUBLE PRECISION,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);