spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:jpa;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
